### ISSUE TITLE
Timer does not start data collection

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#5] opened 2015-03-12 15:17 UTC
Starting the timer does not start data collection.

**Comment by zach-hartwig** [comment] 2015-03-12 16:41
I could not reproduce your issue on hardware (DT5720). After putting appropriate waveform settings in place and creating an ADAQ file, I can check the "Data stored while checked" button or start the acquisition timer. Note that the ADAQ file must be created *before* the acquisition time is started to ensure the ADAQ file is ready to receive data. Both methods show an increasing file size while acquisition is running. ADAQAnalysis is able to open these files and find stored data. Note that one of the three check buttons for data type to be saved must be checked, otherwise nothing will output to the ADAQ file.

Please provide more specifics about your issue.

**Comment by zach-hartwig** [comment] 2015-03-24 21:43
I have not heard any further response to this issue. I am therefore closing this issue. Please let me know if you had/continue to have issues. Thanks.

**Closed by zach-hartwig** 2015-03-24 21:43 UTC
